name: .NET Core Desktop

on:
    pull_request:
        branches:
        - main
        - stable
        - release

jobs:
    build:
        strategy:
          matrix:
            configuration: [Debug, Release]
            
        runs-on: windows-2022

        steps:
        - uses: actions/checkout@v4

        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
              dotnet-version: 4.8.x

        - name: Restore dependencies
          run: dotnet restore

        - name: Run MSBuild
          run: dotnet build --no-restore

        - name: Run Unit Tests
          run: dotnet test --no-build --verbosity-normal
